### ISSUE TITLE
AttributeError: 'HookManager' object has no attribute 'keyboard_hook'

### ISSUE THREAD

**Issue by dschiller** [Tungsteno74/pyWinhook#11]
**Code**

```
import pyWinhook

hm = pyWinhook.HookManager()
```

**Error**

```
Exception ignored in: <function HookManager.__del__ at 0x00000260F1A4E558>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pyWinhook\HookManager.py", line 279, in __del__
    self.UnhookKeyboard()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pyWinhook\HookManager.py", line 299, in UnhookKeyboard
    if self.keyboard_hook:
AttributeError: 'HookManager' object has no attribute 'keyboard_hook'
Exception ignored in: <function HookManager.__del__ at 0x00000260F1A4E558>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pyWinhook\HookManager.py", line 279, in __del__
    self.UnhookKeyboard()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pyWinhook\HookManager.py", line 299, in UnhookKeyboard
    if self.keyboard_hook:
AttributeError: 'HookManager' object has no attribute 'keyboard_hook'
Exception ignored in: <function HookManager.__del__ at 0x00000260F1A4E558>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pyWinhook\HookManager.py", line 279, in __del__
    self.UnhookKeyboard()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pyWinhook\HookManager.py", line 299, in UnhookKeyboard
    if self.keyboard_hook:
AttributeError: 'HookManager' object has no attribute 'keyboard_hook'
```

**Solution**

Open ``HookManager.py`` and change all ``key_hook`` words to ``keyboard_hook``

**Comment by Tungsteno74** [comment]
thanks for contributing :)

**Comment by Ls-Jan** [comment]
Thanks. That's helpful 👍
